language: node_js

node_js: 
    - 14.16.0

addons:
    apt:
        packages:
            - libgconf-2-4

cache:
    npm: true
    directories:
        - ~/.npm
        - ./node_modules
        - ~/.cache
    override:
        - npm ci
        - npm run cy:verify

before_install:
    - npm update

script:
    # - npm run test:coveralls
    - npm run test
    - npm run cy:setup
    - npm run cy:run
    - kill $(jobs -p) || true

deploy:
    provider: azure_web_apps

    on:
        branch: fix-deployment
    
    verbose: true

## Uncomment this if necessary
#after_success:
#- npm run coveralls #check if this is necessary or set up in the coveralls file